language: node_js
node_js:  
  - "node"

install: 
  - npm install

script:
  - npm run lint
  - npm test
  - npm build

deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
